window.GREENLEAF_PRODUCTS=[
{id:'aglaonema-silver-queen',name:'Aglaonema Silver Queen',price:24.99,category:'Aglaonema',image:'https://images.unsplash.com/photo-1593482892290-f54927ae2b3d?auto=format&fit=crop&w=1000&q=90',desc:'Elegant silver-green foliage selected for premium indoor displays.',size:'20–25 cm',light:'Bright, indirect',water:'When top soil dries'},
{id:'philodendron-micans',name:'Philodendron Micans',price:19.99,category:'Philodendron',image:'https://images.unsplash.com/photo-1545165375-27d7d2b5fdb2?auto=format&fit=crop&w=1000&q=90',desc:'Velvety heart-shaped foliage with a refined tropical texture.',size:'25–35 cm',light:'Medium–bright indirect',water:'Moderate'},
{id:'monstera-adansonii',name:'Monstera Adansonii',price:29.99,category:'Monstera',image:'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=1000&q=90',desc:'Distinctive fenestrated leaves for a premium statement display.',size:'30–45 cm',light:'Bright indirect',water:'When top layer dries'},
{id:'scindapsus-pictus',name:'Scindapsus Pictus Exotica',price:22.99,category:'Pothos & Scindapsus',image:'https://images.unsplash.com/photo-1509423350716-97f2360af3c5?auto=format&fit=crop&w=1000&q=90',desc:'Silver-splashed trailing foliage for shelves and hanging planters.',size:'25–40 cm',light:'Medium–bright indirect',water:'Moderate'},
{id:'dracaena-compacta',name:'Dracaena Compacta',price:18.99,category:'Dracaena',image:'https://images.unsplash.com/photo-1593691509543-c55fb32e5cee?auto=format&fit=crop&w=1000&q=90',desc:'Compact architectural foliage for contemporary interiors.',size:'30–45 cm',light:'Medium indirect',water:'Allow partial dry-down'},
{id:'codiaeum-sunny-star',name:'Codiaeum Sunny Star',price:24.99,category:'Croton (Codiaeum)',image:'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=1000&q=90',desc:'Bright colourful croton foliage selected for a bold display.',size:'25–40 cm',light:'Bright light',water:'Keep evenly moist'},
{id:'aglaonema-maria',name:'Aglaonema Maria',price:21.99,category:'Aglaonema',image:'https://images.unsplash.com/photo-1604762524889-3e2fcc145683?auto=format&fit=crop&w=1000&q=90',desc:'Classic patterned foliage with graceful indoor character.',size:'20–30 cm',light:'Low–bright indirect',water:'When top soil dries'},
{id:'monstera-peru',name:'Monstera Peru',price:27.99,category:'Monstera',image:'https://images.unsplash.com/photo-1614594895309-9e1f7f9f1e2d?auto=format&fit=crop&w=1000&q=90',desc:'Textured deeply ribbed foliage for collectors and statement displays.',size:'25–40 cm',light:'Bright indirect',water:'Moderate'}];
window.GL={money:n=>'$'+Number(n).toFixed(2),getCart(){try{return JSON.parse(localStorage.getItem('greenleaf-cart')||'[]')}catch(e){return[]}},saveCart(c){localStorage.setItem('greenleaf-cart',JSON.stringify(c))},getProduct(id){return GREENLEAF_PRODUCTS.find(p=>p.id===id)},items(){return this.getCart().map(x=>({...x,p:this.getProduct(x.id)})).filter(x=>x.p)},add(id,q=1){let c=this.getCart(),x=c.find(i=>i.id===id);x?x.qty+=q:c.push({id,qty:q});this.saveCart(c);this.refresh()},remove(id){this.saveCart(this.getCart().filter(x=>x.id!==id));this.refresh()},setQty(id,q){let c=this.getCart(),x=c.find(i=>i.id===id);if(x)x.qty=Math.max(1,q);this.saveCart(c);this.refresh()},totals(){let i=this.items(),s=i.reduce((a,x)=>a+x.p.price*x.qty,0),sh=s&&s<75?9.95:0;return{subtotal:s,shipping:sh,total:s+sh,count:i.reduce((a,x)=>a+x.qty,0)}},refresh(){let t=this.totals();document.querySelectorAll('[data-cart-count]').forEach(e=>e.textContent=t.count);document.querySelectorAll('[data-cart-subtotal]').forEach(e=>e.textContent=this.money(t.subtotal));document.querySelectorAll('[data-cart-shipping]').forEach(e=>e.textContent=t.shipping?this.money(t.shipping):'FREE');document.querySelectorAll('[data-cart-total]').forEach(e=>e.textContent=this.money(t.total))}};
